export const CHANGE_TEXT_FIELD = 'CHANGE_TEXT_FIELD';
export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const LOAD_USER_INFO_ERROR = 'LOAD_USER_INFO_ERROR';
